import { useState } from 'react';

interface Props {
  slug: string;
  apiBase: string;
  pageUrl: string;
}

/**
 * Small share panel under each TIL post. Three actions:
 *   - Preview — toggle inline preview of the OG image (1200×630 PNG)
 *   - Copy link — clipboard
 *   - Download — save the OG PNG locally as `<slug>-share.png`
 *
 * The image itself is what social platforms (Twitter, LinkedIn, Slack,
 * iMessage, etc.) fetch automatically when someone shares this post's
 * URL — it's wired up via og:image meta tags in Base.astro. This
 * component just exposes the same asset for manual sharing.
 */
export default function TilShare({ slug, apiBase, pageUrl }: Props) {
  const ogUrl = `${apiBase}/api/og/til/${slug}.png`;
  const [showPreview, setShowPreview] = useState(false);
  const [copied, setCopied] = useState(false);
  const [downloading, setDownloading] = useState(false);

  async function copyUrl() {
    try {
      await navigator.clipboard.writeText(pageUrl);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      const ta = document.createElement('textarea');
      ta.value = pageUrl;
      ta.style.position = 'fixed';
      ta.style.opacity = '0';
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      ta.remove();
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    }
  }

  async function downloadImage() {
    if (downloading) return;
    setDownloading(true);
    try {
      const res = await fetch(ogUrl, { credentials: 'include' });
      if (!res.ok) throw new Error('fetch failed');
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${slug}-share.png`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
    } catch {
      window.open(ogUrl, '_blank', 'noopener');
    } finally {
      setDownloading(false);
    }
  }

  return (
    <section className="til-share">
      <div className="til-share__head">
        <span className="til-share__label">// share</span>
        <span className="til-share__hint">auto-applied when you paste this link anywhere</span>
      </div>
      <div className="til-share__row">
        <button
          type="button"
          className={`til-share__btn ${showPreview ? 'is-active' : ''}`}
          onClick={() => setShowPreview((s) => !s)}
        >
          {showPreview ? 'hide preview' : 'preview image'}
        </button>
        <button type="button" className="til-share__btn" onClick={copyUrl}>
          {copied ? '✓ copied' : 'copy link'}
        </button>
        <button
          type="button"
          className="til-share__btn til-share__btn--primary"
          onClick={downloadImage}
          disabled={downloading}
        >
          {downloading ? 'downloading…' : 'download png ↓'}
        </button>
      </div>
      {showPreview && (
        <figure className="til-share__preview">
          <img
            src={ogUrl}
            alt={`Share preview for ${slug}`}
            loading="lazy"
          />
          <figcaption className="til-share__caption">
            1200×630 · generated by Pillow on the backend · auto-served as og:image
          </figcaption>
        </figure>
      )}
    </section>
  );
}
