"""add pinned to guestbook entries

Revision ID: 58ef8fbb9c48
Revises: 20260606_leetcode_username
Create Date: 2026-06-06 18:58:01.277009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58ef8fbb9c48'
down_revision: Union[str, None] = '20260606_leetcode_username'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # `server_default='false'` so existing rows backfill cleanly under
    # NOT NULL. The model carries default=False on the Python side; the
    # server_default is just for this one-time bridge. Drop it after to
    # keep the schema clean — future inserts always specify the column.
    with op.batch_alter_table('guestbook_entries', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('pinned', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.create_index(batch_op.f('ix_guestbook_entries_pinned'), ['pinned'], unique=False)
        batch_op.alter_column('pinned', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guestbook_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guestbook_entries_pinned'))
        batch_op.drop_column('pinned')

    # ### end Alembic commands ###
